### ISSUE TITLE
Enterprise Dashboard

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud-docs/enterprise-dashboard#26]
Issue on page:        https://github.com/opentelekomcloud-docs/enterprise-dashboard/blob/main/doc/source/index.rst

When you navigate from the "Homepage" of the Helpcenter via management -> Other -> Enterprise Dashboard, you will be redirected to the wrong page. 

![image](https://github.com/opentelekomcloud-docs/enterprise-dashboard/assets/79697776/4ce2d4ab-5648-4f4d-b22e-81ee05d26ee4)

After clicking on it, you will be redirected to  https://docs.otc.t-systems.com/developer/iac.html

**Comment by CHS-OTC** [comment]
![image](https://github.com/opentelekomcloud-docs/enterprise-dashboard/assets/79697776/e59a6717-9cd9-469d-83ff-cf0b1469dc9a)

**Comment by hodigy** [comment]
Thanks for the issue report, it's forwarded to the OTC ServiceDesk.
